apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chaos-dr-app
  namespace: chaos-dr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chaos-dr-app
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60   # scale up when CPU > 60%
